routes/web.php
<?php
use App\Http\Controllers\FamiliasController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function () {
    return view('auth.login');
});

/*Calles*/
Route::resource('calles', 'CallesController')->middleware('auth');
Route::post('calles/cambiar_status/{id}', 'CallesController@cambiar_status');

/*Comunas*/
Route::resource('comunas', 'ComunasController')->middleware('auth');
Route::post('comunas/cambiar_status/{id}', 'ComunasController@cambiar_status');

/*Estados Civiles*/
Route::resource('estados_civiles', 'EstadosCivilsController')->middleware('auth');
Route::post('estados_civiles/cambiar_status/{id}', 'EstadosCivilsController@cambiar_status');

/*Etarios*/
Route::resource('etarios', 'EtariosController')->middleware('auth');
Route::post('etarios/cambiar_status/{id}', 'EtariosController@cambiar_status');

/*Etnias*/
Route::resource('etnias', 'EtniasController')->middleware('auth');
Route::post('etnias/cambiar_status/{id}', 'EtniasController@cambiar_status');

/*Inscripciones*/
//Route::resource('inscripciones', 'InscripcionesController')->middleware('auth');

/*Nacionalidades*/
Route::resource('nacionalidades', 'NacionalidadesController')->middleware('auth');
Route::post('nacionalidades/cambiar_status/{id}', 'NacionalidadesController@cambiar_status');

/*Parentescos*/
Route::resource('parentescos', 'ParentescosController')->middleware('auth');
Route::post('parentescos/cambiar_status/{id}', 'ParentescosController@cambiar_status');

/*Periocidades*/
Route::resource('periocidades', 'PeriocidadesController')->middleware('auth');
Route::post('periocidades/cambiar_status/{id}', 'PeriocidadesController@cambiar_status');

/*Poblaciones*/
Route::resource('poblaciones', 'PoblacionesController')->middleware('auth');
Route::post('poblaciones/cambiar_status/{id}', 'PoblacionesController@cambiar_status');

/*Regiones*/
Route::resource('regiones', 'RegionesController')->middleware('auth');
Route::post('regiones/cambiar_status/{id}', 'RegionesController@cambiar_status');

/*Roles*/
//Route::resource('roles', 'RolesController')->middleware('auth');

/*Tipo Eventos*/
Route::resource('tipo_eventos', 'TipoEventosController')->middleware('auth');
Route::post('tipo_eventos/cambiar_status/{id}', 'TipoEventosController@cambiar_status');

/*Eventos*/
Route::resource('eventos', 'EventosController')->middleware('auth');
Route::get('eventos-listado','EventosController@listado')->middleware('auth')->name('eventos.listado');

/*Unidades*/
Route::resource('unidades', 'UnidadesController')->middleware('auth');
Route::post('unidades/cambiar_status/{id}', 'UnidadesController@cambiar_status');

/*Integrantes*/
Route::resource('integrantes', 'IntegrantesController')->middleware('auth');
Route::post('/validar/{rut}', 'IntegrantesController@validar_rut');
Route::post('integrantes/cambiar_status/{id}', 'IntegrantesController@cambiar_status');
Route::get('perfil', function () {
    return view('miembros.miembro');
});


/*Familias*/
Route::resource('familias', 'FamiliasController')->middleware('auth');
Route::delete('familias/{id}', 'FamiliasController@destroy')->middleware('auth');
Route::post('familias/ver/{id}', 'FamiliasController@ver')->middleware('auth');
Route::post('familias/cargar/{id}', 'FamiliasController@cargar')->middleware('auth');
Route::post('familias/salir/{id}', 'FamiliasController@salir')->middleware('auth');
Route::post('familias/anadir/{id}/{fa}', 'FamiliasController@anadir')->middleware('auth');
Route::get('familia', 'FamiliasController@familia_user')->middleware('auth')->name('familia.user');

/*Empresas*/
Route::resource('empresas', 'EmpresasController')->middleware('auth');

/*Productos*/
Route::resource('productos', 'ProductosController')->middleware('auth');

resources/views/home.blade.php
@extends('layouts.admin')
@section('content')

@if(auth::user()->rol_id==0)
{{-- Content-Header --}}
<section class="content-header">
      <h1>
        Panel de Control
        <small>Control general</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Principal</a></li>
        <li class="active">Panel de Control</li>
      </ol>
</section>

{{-- Content --}}
<section class="content">
  <div class="row">
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-yellow">
            <div class="inner">
              <h3>{{ $users }}</h3>

              <p>Usuarios Registrados</p>
            </div>
            <div class="icon">
              <i class="ion ion-person-add"></i>
            </div>
            <a href="{{ route('integrantes.index') }}" class="small-box-footer">Mas información <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-aqua">
            <div class="inner">
              <h3>{{ $empresas }}</h3>

              <p>Empresas</p>
            </div>
            <div class="icon">
              <i class="fa fa-building-o"></i>
            </div>
            <a href="{{ route('empresas.index') }}" class="small-box-footer">Mas información <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-green">
            <div class="inner">
              <h3>0<sup style="font-size: 20px"></sup></h3>

              <p>Tarjetas</p>
            </div>
            <div class="icon">
              <i class="fa fa-credit-card"></i>
            </div>
            <a href="#" title="En Construcción" class="small-box-footer">Mas información <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-red">
            <div class="inner">
              <h3>{{ $events }}</h3>

              <p>Eventos</p>
            </div>
            <div class="icon">
              <i class="fa fa-calendar-check-o"></i>
            </div>
            <a href="{{ route('eventos.index') }}" class="small-box-footer">Mas información <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
  </div>

{{--Lista de Eventos--}}
<div class="box box-primary">
            <div class="box-header ui-sortable-handle" style="cursor: move;">
              <i class="ion ion-clipboard"></i>

              <h3 class="box-title">Proximos Eventos</h3>

            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <!-- See dist/js/pages/dashboard.js to activate the todoList plugin -->
              <ul class="todo-list ui-sortable">
                @foreach ($eventos as $e)
                <li>
                  <!-- drag handle -->
                  <span class="handle ui-sortable-handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                  <!-- checkbox -->
                  <!-- todo text -->
                  <span class="text">{{ $e->name  }}</span>
                  <!-- Emphasis label -->
                    <small class="label label-info"><i class="fa fa-clock-o"></i> {{ $e->created_at }}</small>
                  <!-- General tools such as edit or delete-->
                  <div class="tools">
                    {{--<i class="fa fa-edit"></i>
                    <i class="fa fa-trash-o"></i>--}}
                  </div>
                </li>
                @endforeach
              </ul>
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix no-border">
            </div>
</div>
</section>
@else

{{-- Content-Header --}}
<section class="content-header">
    <h1>
      Bienvenido
      <small>Panel principal</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Principal</a></li>
      <li class="active">Panel principal</li>
    </ol>
</section>

{{-- Content --}}
<section class="content">
<div class="row">      
       <div class="col-lg-6 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-green">
          <div class="inner">
            <h3>5</h3>

            <p>Solicitudes</p>
          </div>
          <div class="icon">
            <i class="fa fa-file-text"></i>
          </div>
          <a href="{{ route('empresas.index') }}" class="small-box-footer">Mas información <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <!-- ./col -->
      <div class="col-lg-6 col-xs-6">
        <!-- small box -->
        <div class="small-box bg-orange">
          <div class="inner">
            <h3>4</h3>
            <p>Pagos</p>
          </div>
          <div class="icon">
            <i class="fa fa-credit-card"></i>
          </div>
          <a href="{{ route('integrantes.index') }}" class="small-box-footer">Mas información <i class="fa fa-arrow-circle-right"></i></a>
        </div>
      </div>
      <!-- ./col -->

</div>

<div class="box box-primary">
    <div class="box-header with-border">
      <h3 class="box-title">Notificaciones</h3>

      <div class="box-tools pull-right">
        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
        </button>
        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <ul class="products-list product-list-in-box">
        <li class="item">
          <div class="product-img">
            <i class="fa fa-check-square fa-2x "></i>
          </div>
          <div class="product-info">
            <a href="javascript:void(0)" class="product-title"> Solicitud de Tarjeta
              <span class="label label-warning pull-right">2019-04-29</span></a>
            <span class="product-description">
                  Procesada
                </span>
          </div>
        </li>
        <!-- /.item -->
        <li class="item">
            <div class="product-img">
              <i class="fa fa-check-square fa-2x "></i>
            </div>
            <div class="product-info">
              <a href="javascript:void(0)" class="product-title"> Aprobacion de Pago
                <span class="label label-warning pull-right">2019-04-28</span></a>
              <span class="product-description">
                  <span class="label label-success">1000,00 $</span>  
                  </span>
            </div>
          </li>
        <!-- /.item -->
      </ul>
    </div>
    <!-- /.box-body -->
    <div class="box-footer text-center">
      <a href="javascript:void(0)" class="uppercase">Ver todas</a>
    </div>
    <!-- /.box-footer -->
  </div>
</section>
@endif
@endsection

resources/views/pdf.blade.php
<!doctype html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

        <title>Laravel y data en PDF | Rimorsoft Online</title>

    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                	@yield('content')
                </div>
            </div>
        </div>
    </body>
</html>