routes/web.php
<?php
use App\Http\Controllers\FamiliasController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function () {
    return view('auth.login');
});

/*Calles*/
Route::resource('calles', 'CallesController')->middleware('auth');
Route::post('calles/cambiar_status/{id}', 'CallesController@cambiar_status');

/*Comunas*/
Route::resource('comunas', 'ComunasController')->middleware('auth');
Route::post('comunas/cambiar_status/{id}', 'ComunasController@cambiar_status');

/*Estados Civiles*/
Route::resource('estados_civiles', 'EstadosCivilsController')->middleware('auth');
Route::post('estados_civiles/cambiar_status/{id}', 'EstadosCivilsController@cambiar_status');

/*Etarios*/
Route::resource('etarios', 'EtariosController')->middleware('auth');
Route::post('etarios/cambiar_status/{id}', 'EtariosController@cambiar_status');

/*Etnias*/
Route::resource('etnias', 'EtniasController')->middleware('auth');
Route::post('etnias/cambiar_status/{id}', 'EtniasController@cambiar_status');

/*Inscripciones*/
//Route::resource('inscripciones', 'InscripcionesController')->middleware('auth');

/*Nacionalidades*/
Route::resource('nacionalidades', 'NacionalidadesController')->middleware('auth');
Route::post('nacionalidades/cambiar_status/{id}', 'NacionalidadesController@cambiar_status');

/*Parentescos*/
Route::resource('parentescos', 'ParentescosController')->middleware('auth');
Route::post('parentescos/cambiar_status/{id}', 'ParentescosController@cambiar_status');

/*Periocidades*/
Route::resource('periocidades', 'PeriocidadesController')->middleware('auth');
Route::post('periocidades/cambiar_status/{id}', 'PeriocidadesController@cambiar_status');

/*Poblaciones*/
Route::resource('poblaciones', 'PoblacionesController')->middleware('auth');
Route::post('poblaciones/cambiar_status/{id}', 'PoblacionesController@cambiar_status');

/*Regiones*/
Route::resource('regiones', 'RegionesController')->middleware('auth');
Route::post('regiones/cambiar_status/{id}', 'RegionesController@cambiar_status');

/*Roles*/
//Route::resource('roles', 'RolesController')->middleware('auth');

/*Tipo Eventos*/
Route::resource('tipo_eventos', 'TipoEventosController')->middleware('auth');
Route::post('tipo_eventos/cambiar_status/{id}', 'TipoEventosController@cambiar_status');

/*Eventos*/
Route::resource('eventos', 'EventosController')->middleware('auth');
Route::get('eventos-listado','EventosController@listado')->middleware('auth')->name('eventos.listado');

/*Unidades*/
Route::resource('unidades', 'UnidadesController')->middleware('auth');
Route::post('unidades/cambiar_status/{id}', 'UnidadesController@cambiar_status');

/*Integrantes*/
Route::resource('integrantes', 'IntegrantesController')->middleware('auth');
Route::post('/validar/{rut}', 'IntegrantesController@validar_rut');
Route::post('integrantes/cambiar_status/{id}', 'IntegrantesController@cambiar_status');
Route::get('perfil', function () {
    return view('miembros.miembro');
});


/*Familias*/
Route::resource('familias', 'FamiliasController')->middleware('auth');
Route::delete('familias/{id}', 'FamiliasController@destroy')->middleware('auth');
Route::post('familias/ver/{id}', 'FamiliasController@ver')->middleware('auth');
Route::post('familias/cargar/{id}', 'FamiliasController@cargar')->middleware('auth');
Route::post('familias/salir/{id}', 'FamiliasController@salir')->middleware('auth');
Route::post('familias/anadir/{id}/{fa}', 'FamiliasController@anadir')->middleware('auth');
Route::get('familia', 'FamiliasController@familia_user')->middleware('auth')->name('familia.user');

/*Empresas*/
Route::resource('empresas', 'EmpresasController')->middleware('auth');

/*Productos*/
Route::resource('productos', 'ProductosController')->middleware('auth');

app/Evento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Periocidad;
use App\TipoEvento;

class Evento extends Model
{
    protected $table = 'eventos';

    protected $fillable = ['name', 'tipo_evento_id', 'cupos', 'fec_ini', 'fec_fin', 'observacion', 'periocidad_id'];

    public function periocidad()
    {

        return $this->belongsTo(Periocidad::class, 'periocidad_id');
    }

    public function tipo_evento()
    {

        return $this->belongsTo(TipoEvento::class, 'tipo_evento_id');
    }
}

app/Http/Controllers/EventosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Session;
use App\Evento;
use App\TipoEvento;
use App\Periocidad;

class EventosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $eventos = Evento::with('periocidad','tipo_evento')->get();
        $tipo = TipoEvento::where('status', 1)->get();
        $periodos = Periocidad::where('status', 1)->get();
        return view('eventos.index', compact('periodos', 'tipo', 'eventos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validamos que los datos cumplan con los requisitos
        $validar = Validator::make(
            $request->all(),
            ['name' => 'required|unique:eventos|min:3', 'tipo' => 'required', 'inicio' => 'required', 'final' => 'required', 'cupos' => 'required', 'periocidad' => 'required'],
            ['required' => 'Campo Requerido', 'unique' => 'Ya existe un evento con ese nombre', 'min' => 'Longitud minima permitida 3 caracteres']
        );

        //Si existen errores
        if (count($validar->errors()) > 0) {

            //Retornamos cada uno de los errores
            return response()->json(['status' => 500, 'errors' => $validar->errors()]);
        }
        //Si no creamos el registro
        else {


            $evento = new Evento();
            $evento->name = $request->name;
            $evento->tipo_evento_id = $request->tipo;
            $evento->cupos = $request->cupos;
            $evento->fec_ini = $request->inicio;
            $evento->fec_fin = $request->final;
            $evento->periocidad_id = $request->periocidad;
            if (!$request->observacion) {

                $evento->observacion = "Sin Observaciones";
              }else{ 
                $evento->observacion = $request->observacion; 
              }
            $evento->save();


            Session::flash('message', 'Se ha registrado el evento: ' . $evento->name);
            Session::flash('class', 'success');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $evento = Evento::find($id);
        $name = $evento->name;
        $evento->delete();

        Session::flash('message', 'Se ha eliminado el evento: ' . $name);
        Session::flash('class', 'danger');
    }

    public function listado()
    {   
        $eventos = Evento::with('periocidad','tipo_evento')->get();
        //$tipo = TipoEvento::where('status', 1)->get();
        //$periodos = Periocidad::where('status', 1)->get();
        return view('miembros.listado', compact( 'eventos'));
    }
}

resources/views/eventos/index.blade.php
@extends('layouts.admin')
@section('content')

<!--Ubicacion-->
<section class="content-header">
      <h1>
        Gestion de Eventos
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Tarjeta Vecinos</a></li>
        <li><a href="#">Eventos</a></li>

      </ol>
      <!--Alerta de Eventos-->           
</section>
            
<!--Seccion para el contenido-->
<section class="content" id="content">
                  @if (session('message'))
                     <div class="alert alert-{{ session('class') }} mt-3">

                     <h4><i class="icon fa fa-check"></i>{{ session('message')}}</h4>

                     </div>       
                  @endif
                  <div class="row">
                        <div class="col-md-12">
                                    <div class="box box-success">
                                      <div class="box-header with-border">
                                        <h3 class="box-title">Listado de Eventos</h3>
                                        <button class="btn btn-primary" style="float: right;" data-target='#evento_crear' data-toggle='modal'>Registro de Evento</button>
                                      </div>
                                      <!-- /.box-header -->
                                      <div class="box-body">
                                        <table class="table table-bordered" id="lista">
                                          <thead>
                                                <tr>
                                                <th style="width: 10px">#</th>
                                                <th>Evento</th>
                                                <th>Tipo de Eventos</th>
                                                <th>Cupos</th>
                                                <th>Fecha de Inicio</th>
                                                <th>Fecha de Final</th>
                                                <th>Acciones</th>
                                                </tr>
                                          </thead>
                                           <tbody>
                                             @foreach ($eventos as $event)
                                             <tr>
                                              <td>{{ $event->id}}</td>
                                              <td>{{ $event->name }}</td>
                                              <td>{{ $event->tipo_evento->name }}</td>
                                              <td><span class="label label-info">{{ $event->cupos }}</span></td>
                                              <td>{{ $event->fec_ini }}</td>
                                              <td>{{ $event->fec_fin}}</td>
                                              <td> <button class="btn btn-danger" onclick="evento_eliminar('{{ $event->id }}')"><i class="fa fa-trash"></i></button></td>
                                            </tr>    
                                             @endforeach
                                           </tbody>
                                      </table>
                                      </div>
                                      <!-- /.box-body -->
                                    </div>
                            <!-- /.box -->
                  </div>
</div>

<div class="modal fade" id="evento_crear">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span></button>
                <h4 class="modal-title">Registrar Evento</h4>
              </div>
              <div class="modal-body">
                    <form action="{{ route('eventos.store') }}" method="POST">

                                  @csrf

                              <div class="box-body">
                              <div class="form-group">
                                      <label for="exampleInputEmail1">Nombre del Evento:</label>
                                      <input type="text" name="name" id="name" class="form-control" placeholder="Ej: Domingo Familiar, ..." required="required" min="5">
                                      <span id="name_error" class="label label-danger" style="display:none"></span>
                              </div>
                              <div class="form-group">
                                      <label for="exampleInputPassword1">Tipo de Evento</label>
                                      <select class="form-control" name="tipo_evento_id" id="tipo_evento_id" required="required">
                                        <optgroup>
                                          <option selected="selected" disabled="disabled">-- Seleccione --</option>
                                          @foreach ($tipo as $t)
                                          <option value="{{ $t->id }}">{{ $t->name }}</option>    
                                          @endforeach
                                        </optgroup>
                                      </select>
                                      <span id="tipo_error" class="label label-danger" style="display:none"></span>
                               </div>
                               <div class="row">
                               <div class="form-group col-md-6">
                                      <label for="exampleInputEmail1">Fecha de Inicio:</label>
                                      <input type="date" class="form-control" name="fec_ini" id="fec_ini" required="required">
                                      <span id="ini_error" class="label label-danger" style="display:none"></span>
                               </div>
                               <div class="form-group col-md-6">
                                      <label for="exampleInputEmail1">Fecha de Finalizacion:</label>
                                      <input type="date" class="form-control" name="fec_fin" id="fec_fin" required="required">
                                      <span id="fin_error" class="label label-danger" style="display:none"></span>
                               </div>
                               </div>
                               <div class="row">
                               <div class="form-group col-md-6">
                                      <label for="exampleInputEmail1">Cupos Disponibles:</label>
                                      <input type="number" min="1" class="form-control" name="cupos" id="cupos" required="required">
                                      <span id="cupos_error" class="label label-danger" style="display:none"></span>
                               </div>
                               <div class="form-group col-md-6">
                                      <label for="exampleInputEmail1">Periocidad:</label>
                                      <select class="form-control" name="periocidad_id" id="periocidad_id" required="required">
                                        <optgroup>
                                          <option selected="selected" disabled="disabled">-- Seleccione --</option>
                                          @foreach ($periodos as $p)
                                          <option value="{{ $p->id }}">{{ $p->name }}</option>    
                                          @endforeach
                                        </optgroup>
                                      </select>
                                      <span id="per_error" class="label label-danger" style="display:none"></span>
                                </div>
                               </div>
                               <div class="form-group">
                                      <label for="exampleInputEmail1">Observacion:</label>
                                      <textarea class="form-control" name="observacion" id="observacion" required="required"></textarea>
                                    </div>
                               </div>
                                  <!-- /.box-body -->
              </div>
              <div class="modal-footer">
                  <div class="col-md-12 text-center">
                  <button type="button" onclick="evento_guardar()" class="btn btn-success">Guardar Evento</button>
                  </div>
              </div>
            </div>
            <!-- /.modal-content -->
          </div>
          <!-- /.modal-dialog -->
</div>
</section>

@endsection