routes/web.php
<?php
use App\Http\Controllers\FamiliasController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', function () {
    return view('auth.login');
});

/*Calles*/
Route::resource('calles', 'CallesController')->middleware('auth');
Route::post('calles/cambiar_status/{id}', 'CallesController@cambiar_status');

/*Comunas*/
Route::resource('comunas', 'ComunasController')->middleware('auth');
Route::post('comunas/cambiar_status/{id}', 'ComunasController@cambiar_status');

/*Estados Civiles*/
Route::resource('estados_civiles', 'EstadosCivilsController')->middleware('auth');
Route::post('estados_civiles/cambiar_status/{id}', 'EstadosCivilsController@cambiar_status');

/*Etarios*/
Route::resource('etarios', 'EtariosController')->middleware('auth');
Route::post('etarios/cambiar_status/{id}', 'EtariosController@cambiar_status');

/*Etnias*/
Route::resource('etnias', 'EtniasController')->middleware('auth');
Route::post('etnias/cambiar_status/{id}', 'EtniasController@cambiar_status');

/*Inscripciones*/
//Route::resource('inscripciones', 'InscripcionesController')->middleware('auth');

/*Nacionalidades*/
Route::resource('nacionalidades', 'NacionalidadesController')->middleware('auth');
Route::post('nacionalidades/cambiar_status/{id}', 'NacionalidadesController@cambiar_status');

/*Parentescos*/
Route::resource('parentescos', 'ParentescosController')->middleware('auth');
Route::post('parentescos/cambiar_status/{id}', 'ParentescosController@cambiar_status');

/*Periocidades*/
Route::resource('periocidades', 'PeriocidadesController')->middleware('auth');
Route::post('periocidades/cambiar_status/{id}', 'PeriocidadesController@cambiar_status');

/*Poblaciones*/
Route::resource('poblaciones', 'PoblacionesController')->middleware('auth');
Route::post('poblaciones/cambiar_status/{id}', 'PoblacionesController@cambiar_status');

/*Regiones*/
Route::resource('regiones', 'RegionesController')->middleware('auth');
Route::post('regiones/cambiar_status/{id}', 'RegionesController@cambiar_status');

/*Roles*/
//Route::resource('roles', 'RolesController')->middleware('auth');

/*Tipo Eventos*/
Route::resource('tipo_eventos', 'TipoEventosController')->middleware('auth');
Route::post('tipo_eventos/cambiar_status/{id}', 'TipoEventosController@cambiar_status');

/*Eventos*/
Route::resource('eventos', 'EventosController')->middleware('auth');
Route::get('eventos-listado','EventosController@listado')->middleware('auth')->name('eventos.listado');

/*Unidades*/
Route::resource('unidades', 'UnidadesController')->middleware('auth');
Route::post('unidades/cambiar_status/{id}', 'UnidadesController@cambiar_status');

/*Integrantes*/
Route::resource('integrantes', 'IntegrantesController')->middleware('auth');
Route::post('/validar/{rut}', 'IntegrantesController@validar_rut');
Route::post('integrantes/cambiar_status/{id}', 'IntegrantesController@cambiar_status');
Route::get('perfil', function () {
    return view('miembros.miembro');
});


/*Familias*/
Route::resource('familias', 'FamiliasController')->middleware('auth');
Route::delete('familias/{id}', 'FamiliasController@destroy')->middleware('auth');
Route::post('familias/ver/{id}', 'FamiliasController@ver')->middleware('auth');
Route::post('familias/cargar/{id}', 'FamiliasController@cargar')->middleware('auth');
Route::post('familias/salir/{id}', 'FamiliasController@salir')->middleware('auth');
Route::post('familias/anadir/{id}/{fa}', 'FamiliasController@anadir')->middleware('auth');
Route::get('familia', 'FamiliasController@familia_user')->middleware('auth')->name('familia.user');

/*Empresas*/
Route::resource('empresas', 'EmpresasController')->middleware('auth');

/*Productos*/
Route::resource('productos', 'ProductosController')->middleware('auth');

app/Http/Controllers/NacionalidadesController.php
<?php

namespace App\Http\Controllers;

use App\Nacionalidad;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class NacionalidadesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $nacionalidades = Nacionalidad::all();
       return view('nacionalidades.index', compact('nacionalidades'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(['name' => 'required|min:4|unique:nacionalidades'],['name.required' => 'Campo Requerido', 'name.min' => 'Longitud Minima de 4 Caracteres', 'name.unique' => 'Este Estado Civil ya existe, verifique el listado']);

        $Nacionalidades = new Nacionalidad();
        $Nacionalidades->name = $request->name;
        $Nacionalidades->save();

        Session::flash('message','Se ha creado la Nacionalidad: '.$request->name.'!' );
        Session::flash('class','success');

        return redirect('/nacionalidades');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function cambiar_status($id)
    {

        /*Consultamos la nacionalidad a modificar*/
        $nacionalidad = Nacionalidad::find($id);
        
        /*Si la nacionalidad esta activada => desactivala*/
        if ($nacionalidad->status == 1) {
            
            $nacionalidad->status = 0;
            $nacionalidad->save();

            Session::flash('message', 'Se ha desactivado a la nacionalidad:'.' '.$nacionalidad->name);
            Session::flash('class', 'danger');

        /*Si la nacionalidad esta desactivada => activada*/
        }else if ($nacionalidad->status == 0) {
            
            $nacionalidad->status = 1;
            $nacionalidad->save();

            Session::flash('message', 'Se ha activado a la nacionalidad:'.' '.$nacionalidad->name);
            Session::flash('class', 'info');    
        }

    }
}

resources/views/nacionalidades/index.blade.php
@extends('layouts.admin')
@section('content')

<!--Ubicacion-->
<section class="content-header">
      <h1>
        Gestion de Nacionalidades
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Tarjeta Vecinos</a></li>
        <li><a href="#">Nacionalidades</a></li>

      </ol>
      <!--Alerta de Eventos-->           
</section>
            
<!--Seccion para el contenido-->
<section class="content" id="content">
                  @if (session('message'))
                     <div class="alert alert-{{ session('class') }} mt-3">

                     <h4><i class="icon fa fa-check"></i>{{ session('message')}}</h4>

                     </div>       
                  @endif
                  <div class="row">
                        
                        <div class="col-md-6">
                        
                                <div class="box box-primary">

                                  <div class="box-header with-border">
                                    <h3 class="box-title">Crear Nacionalidad</h3>
                                  </div>
                                  <!-- /.box-header -->
                                            <!-- form start -->
                                            <form role="form" action="{{ route('nacionalidades.store') }}" method="POST">
                                            <div class="box-body">

                                                @csrf

                                                  <div class="form-group{{ $errors->has('name') ? 'has-error' : '' }} col-md-12">

                                                        <label for="exampleInputEmail1">Nombre:</label>
                                                        <input type="text" class="form-control" min="4" name="name" value="{{ old('name') }}" placeholder="Nombre..." required="required" autofocus="autofocus">
                                                        <span class="help-block label label-danger">{{ $errors->first('name') }}</span>

                                                  </div>

                                          </div>
                                                    <!-- /.box-body -->

                                                  <div class="box-footer text-center">
                                                    <button type="submit" class="btn btn-primary">Guardar</button>
                                                    <button type="reset" class="btn btn-default">Cancelar</button>
                                                  </div>
                                            </form>
                                 </div>

                        </div>

                        <div class="col-md-6">
                                    <div class="box box-success">
                                      <div class="box-header with-border">
                                        <h3 class="box-title">Listado de Nacionalidades</h3>
                                      </div>
                                      <!-- /.box-header -->
                                      <div class="box-body">
                                        <table class="table table-bordered" id="lista">
                                          <thead>
                                                <tr>
                                                <th style="width: 10px">#</th>
                                                <th>Nacionalidad</th>
                                                <th>Estado</th>
                                                <th style="width: 40px">Acciones</th>
                                                </tr>
                                          </thead>
                                           <tbody>
                                            @foreach($nacionalidades as $c)
                                             <tr>
                                               <td>{{ $loop->iteration }}</td>
                                               <td>{{ $c->name }}</td>
                                               <td>
                                                @if($c->status==1)
                                                   <span class="label label-primary">Activo</span>
                                                @else
                                                   <span class="label label-default">Desactivado</span>  
                                                @endif 
                                               </td>
                                               <td>
                                                @if($c->status==1)
                                                <button class="btn btn-danger" title="Desactivar" onclick="nacionalidad_status('{{ $c->id }}')">
                                                  <i class="fa fa-pause"></i>
                                                </button>
                                                @else
                                                <button class="btn btn-success" title="Activar" onclick="nacionalidad_status('{{ $c->id }}')">
                                                  <i class="fa fa-play"></i>
                                                </button>
                                               @endif 
                                               </td>
                                             </tr>
                                            @endforeach
                                           </tbody>
                                      </table>
                                      </div>
                                      <!-- /.box-body -->
                                    </div>
                                    <!-- /.box -->
                           </div>

                  </div>
</section>


@endsection